name: get-pca-data

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1                                                                 
      - name: 🐍 Set up Python 3.10.8                              
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.10'                                                   
      - name: 💿 Install Requirements                             
        run: pip install -r requirements.txt
      - name: 🍳 Update dataset
        run: python get_pca_data.py
      - name: 🚀 Commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
